### ISSUE TITLE
does not work on iOS 64bit 

### ISSUE THREAD

**Issue by hpoulsen** [TurboPack/LockBox#1]
Can not build with iOS 64bit as target!

All  lbxxxStream object is not compiling to iOS 64 bit !  

on lbxxxStream object the read and write functions are defined with integer, but in TMemoryStream  
they are LongInt 

```
function Read(var Buffer; Count : Integer) : Integer; override;
function Write(const Buffer; Count : Integer) : Integer; override;
```

Longint and Integer is not the same on iOS 64 bit!!

**Comment by romankassebaum** [comment]
Fixed.
