### ISSUE TITLE
C++ Builder files were not created with the default installer for 10.3.3 Rio

### ISSUE THREAD

**Issue by jaridmo** [TurboPack/LockBox#10]
Running the GetIt package installer for RadStudio the LockBox package was not compiled for C++ Builder (Missing all the hpp files).  
Also the paths in the Tools - Options - C++ - Paths and Directories - System Include Path contained $(BDSCatalogRepository)\LockBox-2.4\source\hpp\Win32\Debug but when I opened and recompiled the packages the hpp files were placed in the source folder so the path needed to be changed to $(BDSCatalogRepository)\LockBox-2.4\source\

**Comment by romankassebaum** [comment]
Shipping the hpp files makes no sense for several reasons. The user can always create them himself. The output folder in the package in the default output folder.
