### ISSUE TITLE
Empty component list after update to 2.5 in Delphi 10.4

### ISSUE THREAD

**Issue by szwajcar** [TurboPack/LockBox#14]
After update components via GetIt package list "Installed components" is empty:
![obraz](https://user-images.githubusercontent.com/24227245/90819718-9cfd4200-e330-11ea-80cc-395145806ef3.png)

**Comment by romankassebaum** [comment]
The package "TurboPack LockBox Delphi designtime package" is missing. It contains the components. I will ask EMBT if there is an issue during installation.

**Comment by romankassebaum** [comment]
And I have forgotten to mention that "TurboPack LockBox Delphi Vcl designtime package" contains only property and component editors.
