### ISSUE TITLE
Example ? documentation ?

### ISSUE THREAD

**Issue by jcp2024dev** [TurboPack/LockBox#20]
I can't find an example or documentation on how to use the components to decrypt.
What properties to use to decrypt a 128-bit AES/CBC string with AES/CBC/PKCS5PADDING ?

**Comment by romankassebaum** [comment]
I would recommend to use this library in legacy projects. For new ones there are better solutions.

**Comment by jcp2024dev** [comment]
Thanks for the advice, you’re right
Greetings

Jero Coves
DEPTO. SOFTWARE


[Query Informática S.L.]

C/. ESPRONCEDA, 113 | 03204 ELCHE (ALICANTE)
966 640 687<tel:+34966640687> | www.query.es<https://www.query.es/> | ***@***.******@***.***>

Síguenos en: Twitter<https://twitter.com/QueryInforma> | Facebook<https://www.facebook.com/queryinformatica/> | LinkedIn<https://www.linkedin.com/company/queryinformatica> | Blog<https://www.query.es/blog>


AVISO LEGAL: La información contenida en este correo electrónico, y en su caso en los documentos adjuntos, es información privilegiada para uso exclusivo de la persona y/o personas a las que va dirigido. No está permitido el acceso a este mensaje a cualquier otra persona distinta a los indicados. Si Usted no es uno de los destinatarios, cualquier duplicación, reproducción, distribución, así como cualquier uso de la información contenida en él o cualquiera otra acción u omisión tomada en relación con el mismo, está prohibida y puede ser ilegal. En dicho caso, por favor notifíquelo al remitente y proceda a la eliminación de este correo electrónico así como de sus adjuntos si los hubiere.
Asimismo y en cumplimiento de Ley Orgánica 3/2018 de protección de datos de carácter personal y garantía de los derechos digitales y del Reglamento Europeo RGPD 679/2016 le informamos que sus datos están siendo objeto de tratamiento por parte de QUERY INFORMATICA, SL con NIF B53210167, con la finalidad del mantenimiento y gestión de relaciones comerciales y administrativas. La base jurídica del tratamiento es el cumplimiento de la legislación fiscal, mercantil y contable. No se prevén cesiones y/o transferencias internacionales de datos. Para ejercitar sus derechos puede dirigirse a QUERY INFORMATICA, SL domiciliada en C/ ESPRONCEDA, 113 - 03204 ELCHE (Alicante), o bien por email a ***@***.******@***.***>, con el fin de ejercer sus derechos de acceso, rectificación, supresión (derecho al olvido), limitación de tratamiento, portabilidad de los datos, oposición, y a no ser objeto de decisiones automatizadas, indicando como Asunto: “Derechos Ley Protección de Datos”, y adjuntando fotocopia de su DNI o documento identificativo equivalente.



De: Roman Kassebaum ***@***.***>
Enviado el: miércoles, 3 de julio de 2024 23:54
Para: TurboPack/LockBox ***@***.***>
CC: Jerónimo Coves (Query Informática S.L.) ***@***.***>; Author ***@***.***>
Asunto: Re: [TurboPack/LockBox] Example ? documentation ? (Issue #20)


I would recommend to use this library in legacy projects. For new ones there are better solutions.
