### ISSUE TITLE
TCodec.DecryptStream compatibility

### ISSUE THREAD

**Issue by guetin** [TurboPack/LockBox#4]
Previously I was using SeanBDurkin/tplockbox 3.6.3.0. I installed the Delphi 10 Seattle LockBox 3.5.0 package from IDE GetIt and I cannot get my previous crypted files to be decrypted with TCodec.DecryptStream. Are the two versions compatibles ? Here is my components configuration :

  object Codec1: TCodec
    AsymetricKeySizeInBits = 1024
    AdvancedOptions2 = []
    CryptoLibrary = CryptographicLibrary1
    Left = 616
    Top = 24
    StreamCipherId = 'native.StreamToBlock'
    BlockCipherId = 'native.3DES.1'
    ChainId = 'native.CBC'
  end
  object CryptographicLibrary1: TCryptographicLibrary
    Left = 624
    Top = 88
  end

Thanks

**Comment by romankassebaum** [comment]
You should ask Sean directly. He is also part of the LockBox3 GetIt project.
