### ISSUE TITLE
Missing LockBox.inc in LBBytes.pas

### ISSUE THREAD

**Issue by MaxJaisle** [TurboPack/LockBox#5]
Using the RSA encryption / decryption I got a range check error in TLbBase64.LbDecodeBase64.
I added {$I LockBox.inc} to LbBytes.pas to avoid this.

**Comment by romankassebaum** [comment]
Fixed.

**Comment by MaxJaisle** [comment]
Thanks.

 Ursprüngliche Nachricht 
 Absender:  Roman Kassebaum notifications@github.com
 Gesendet am:  24.11.2015 15:50:30
 Betreff:  Re: [LockBox] Missing LockBox.inc in LBBytes.pas (#5)
 Empfänger:  TurboPack/LockBox LockBox@noreply.github.com
 CC:  MaxJaisle max.jaisle@cas.de

Fixed.
