### ISSUE TITLE
LbRijndael EncodeString and DecodeString issue

### ISSUE THREAD

**Issue by sgeeroms** [TurboPack/LockBox#7]
Hi,

I found an issue with the EncodeString and DecodeString methods in LbRijndael, but it is an issues in other cypher classes as well.
I think the EncodeString should return an AnsiString and the DecodeString should have an AnsiString as in parameter. More precisely it is an error i think that the EncodeString uses the internal GetString method that relies on the encoding of the given string to encrypt. but the generated encrypted data should always be interpreted ans ANSI and not use the encrypted data encoding. This behaviour is what we had in the previous 2.08 version of LockBox that still made a distinction between unicode and none unicode methods.
I suggest changing this behaviour by adding a protected GetBytesString method that is used to return keys and cyphers as string instead of the now used GetString method.
But this will change the existing behaviour of the LockBox components.

regards,
Steve

**Comment by romankassebaum** [comment]
I cannot find LbRijndael.
