### ISSUE TITLE
Support D7 and Tokyo Linux

### ISSUE THREAD

**Issue by surroundbr** [TurboPack/LockBox#8]
Please, make installation compatible with Delphi 7, need some adjusts, like TBytes doesnt is available on D7.
And will be so cool if support last Delphi Tokyo to linux.

**Comment by romankassebaum** [comment]
Delphi 7 will not be supported.

The Tokyo version can be found here: https://github.com/TurboPack-Tokyo/LockBox

**Comment by surroundbr** [comment]
Roman,

	Thanx for your replie, components almost close to perfect, compile 50% my code, I cannot found inside pack the unit “LbString.pas”, there is no port of this unit?

	Thanx!

**Comment by romankassebaum** [comment]
I have no idea about this unit.
