### ISSUE TITLE
GenerateMD5Key

### ISSUE THREAD

**Issue by Perceptionist** [TurboPack/LockBox#9]
In TMD5.GenerateMD5Key the Key is never returned.

Changed was to add Key := TKey128(D) 
class procedure TMD5.GenerateMD5Key(var Key : TKey128; const ABytes: TBytes);
var
  D: TMD5Digest;
begin
  HashMD5(D, ABytes[0], Length(ABytes));
  **Key := TKey128(D);**
end;

**Comment by romankassebaum** [comment]
Fixed.

**Comment by Perceptionist** [comment]
THANKS, is the approach I took the acceptable one?

I downloaded with the Gitit Manager in the IDE RIO 10.3.2 – but there wasn’t an option to create a branch.

THANKS

John C. La Rue

Perceptionist Inc
178 W. Schrock Rd
Westerville, OH 43081
